### ISSUE TITLE
G-005: Information Extensibility

### ISSUE THREAD

**Issue by jimsch** [sacmwg/draft-ietf-sacm-requirements#11]
Version -04
1.  What are you trying to avoid collisions on?  Is this for standard and non-standard ways of defining the same attribute?  Are we talking about having multiple ways of mapping from the information model to the data model?  It may also be that we are talking about collisions of attributes that are coming from different non-standard lists.   
2.  Is this requirement applicable to information model, to data model or both?  When external lists of attributes come into scope, are they expected to be expressed as an information model or as a data model?
3.  Does the SHOULD apply to the ability to express standard and non-standard attribute, or to the ability to avoid collisions.  I assume the first is an absolute requirement to meet requirement G-001.  So the issue is collisions.  Thus the question, under what circumstances is it ok to allow for collisions to occur?
4.  These attributes are being defined as mandatory where?  Does this really mean that all of the information models should have a statement on which attributes are required to be propagated into the data model and which are not?  Or are we talking about pieces of attributes such as data types?

**Comment by ncamwing** [comment]
Hi Jim,
I think you mean G-006 "Extensibility"....to comment on your points:
1. We should avoid name collisions in the standard attribute definitions as data models are mapped to the information model.....I think it will be hard to enforce non-standard attribute definitions that may collide.  But say, if the information model defines a "software version" attribute to be a string (vs. a number), then the data model should map directly to it (vs. overriding it, say to be a numeric value as that would be a type of collision).  Similarly, non-standard attribute names may collide but I am not sure how we can enforce such avoidance?
1. Given that there's a single SACM information model, I think the collisions are more about the data model (though since this is general, we do need to ensure we don't mess up and create collisions in the IM too).
2. The SHOULD is to avoid collisions (perhaps a MUST for the information model and for the standard base but a SHOULD for the non-standard). 
3. The attributes are defined in the information model with the mandatory ones to be highlighted to ensure the data models include them.

If you have suggestions for language improvements let me know!

Thanks, Nancy

**Comment by llorenzin** [comment]
To Nancy's comment "Similarly, non-standard attribute names may collide but I am not sure how we can enforce such avoidance?" - One way to avoid attribute name collisions is to require a unique well-defined prefix (such as the 24-bit SMI Private Enterprise Number Vendor ID, which is what TCG uses to avoid name collisions for vendor-defined elements) on the name.

**Comment by ncamwing** [comment]
I think there are ways to define mechanisms to avoid collisions, my point is that SACM can not really enforce it as it is implementation based.

That is, from a specification (vs. requirement) we can specify how attributes can be defined to avoid collisions.....but am not sure we put that as a requirement?

**Comment by jimsch** [comment]
Information Extensibility:  Non-standard (implementation-specific) data attributes MUST be supported.  A method SHOULD be defined for preventing collisions from occurring in the naming of all data attributes independent of their source.  For interoperability and scope boundary, the information model MUST define the mandatory set of data attributes.   The set of attributes defined by the information model MUST be well defined.

**Comment by ncamwing** [comment]
I like this wording much better, updated in -06.

Thanks, Nancy

**Comment by jimsch** [comment]
Fixed in -06
