### ISSUE TITLE
IM-001: Extensible Attribute Dictionary

### ISSUE THREAD

**Issue by jimsch** [sacmwg/draft-ietf-sacm-requirements#24]
Version -04
1.  I have a problem with the word 'minimum' in this requirement.  What do you mean by this?  That it must define a 'sufficient set of attributes' or that it cannot define any additional attributes beyond the minimum set of attributes that is required?  
2.  The second sentence seems odd to me.   Firstly, the current IM that is in the WG does not seem to have any type of dictionary in it, let along one that is extensible.  Secondly, why would an IM have an extensible set of attributes?   I do not believe that there is currently a requirement that a DM is restricted to the set of items in an IM, it can add more things on its own.  The question then is what happens when an IM or a portion of an IM is updated.   What would happen if an IM eliminated elements.  This is a similar sort of issue, the DM might still keep those attributes for evaluation engines to check.  I need more context to understand what is being discussed in this sentence.

**Comment by ncamwing** [comment]
Hi Jim,

Please suggest a better wording....the intent is to ensure that the information model provides a required set (e.g. minimally) to ensure interoperability between data models.  But also, I think there can be a very large set of attributes to achieve "posture", so the information model has to define the MUST (as 'the' minimum set) of attributes that a data model must support.

Again, I am going by the basis that there is a single SACM information model that a data model must meet requirements.....a data model could be extended to have its own attributes but that could be for vendor differentiation or because there may be different types of applications (e.g. there may be apps that do more than posture so the data model would be richer in that sense).  

Does that help?
   Nancy.

**Comment by llorenzin** [comment]
Suggestion: 
IM-001  Extensible Attribute Dictionary: the Information Model MUST
    define a minimum set of attributes for communicating Posture
    Information, to ensure interoperability between data models. (Individual data models may define attributes beyond the mandatory-to-implement minimum set.)  The attributes should be defined with a clear mechanism for extensibility to enable data models to adhere to SACM's required attributes as well as allow for their own extensions.

**Comment by jimsch** [comment]
That is a clear requirement.  And it very clearly expresses what is a DM requirement that needs to be adhered to.  Should there be a sentence along the lines of "The attribute dictionary should be defined with a clear mechanism for extensibility to enable future versions of the information model to be expanded with new attributes."

**Comment by ncamwing** [comment]
I think the added sentence to Lisa's updates makes sense as well....will do in -05

**Comment by jimsch** [comment]
Looks fine to me.
