### ISSUE TITLE
DM-002: <no pithy title>

### ISSUE THREAD

**Issue by jimsch** [sacmwg/draft-ietf-sacm-requirements#27]
Version -04
1.  There is no pity title for this requirement and thus does not follow the previous structure
2.  This is stating that DMs can be structured.  Should there be a similar requirement that IMs can be structured?  Possible this is really an IM requirement.  
3.  If I am implementing a customer against an IM, should I be expected to need to know that the DM is broken down into multiple modules?  It the requirement really that while the DM can be structured, from a query point of view it should not appear to be broken down that way.
4.  If a DM can be structured, what happens if there are multiple DMs that can represent a submodule?  Does the customer need to negoitate just the DM or does it need to negotiate all of the submodule DMs as well?

**Comment by ncamwing** [comment]
Hi Jim,
The information model should not dictate any specific structure; though i would think a data model would infer one.  That is, some applications may choose a relational vs. graph structure or an unstructured model altogether but that imho is not to be forced by the information model.

To your #3, implementation should not be specified in the IM....again that is up to the DM's implementation (and even there, I may leave implementation out of scope as there may be optimizations a vendor may use to better render their version of a DM).....so I'm not sure how a DM may be broken into well defined modules as that may be implementation specific details?

```
 Nancy.
```

**Comment by jimsch** [comment]
Again you are thinking in terms of the one true SACM IM and I am not.  I am assuming that, just like the DM, the IM can be broken down into sub modules that reference each other and can be updated independently.

I was not expecting this to be a statement of how the database undelying the DM is implemented.  If that is what you want to be saying then I would completely rewrite this requirement to directly address that issue to make it clear.

Relative to #3, I was asking if the structure of the DM is hidden to the application, or if the structure of the DM must be well understood by the application.

**Comment by ncamwing** [comment]
Hi Jim,
I am still presuming 1 IM (else I'd have to change the requirements and architecture I think?)....but I think we are converging in thoughts to why 1 IM now given the SACM thread?

Thanks, Nancy

**Comment by llorenzin** [comment]
To #4 (If a DM can be structured, what happens if there are multiple DMs that can represent a submodule? Does the customer need to negoitate just the DM or does it need to negotiate all of the submodule DMs as well?) - I don't see how negotiating all the submodule DMs could be avoided.  

To #3 (If I am implementing a customer against an IM, should I be expected to need to know that the DM is broken down into multiple modules? Is the requirement really that while the DM can be structured, from a query point of view it should not appear to be broken down that way.) - Ideally the DM should appear as one data model to a querent even if it's constructed of multiple hierarchical DMs.

It seems that the theory here is that the querent negotiates all the data model modules, assembles the individual modules into the superset data model, and then queries it as one data model. Is that reasonable in practice?

**Comment by jimsch** [comment]
Making a "super" data model makes sense in theory.  It will be interesting to see if it works in practice.

**Comment by jimsch** [comment]
DM-002 Data Model Structure:  The data model can be structured either monolithically or into modules and sub-modules that allow for references between them.  The data model structure MAY reflect structure in the information model, but does not need to.  For example, the data model may use one module to define endpoints, and that module will reference other modules that describe the various assets associated with the endpoint.  Constraints and interfaces may further be defined to resolve or tolerate ambiguity in the references (e.g. same IP address used in two separate networks).

**Comment by ncamwing** [comment]
Hi Jim,  I will add your clarifications, but if it's OK, I changed "monolithically or into" to "as one single module or separated into"

Will show up in 06.

Thanks, Nancy

**Comment by jimsch** [comment]
That is fine.

**Comment by jimsch** [comment]
Fixed in -06
