### ISSUE TITLE
ARCH-NEW: Component Identification

### ISSUE THREAD

**Issue by jimsch** [sacmwg/draft-ietf-sacm-requirements#34]
Version -04

Suggested new requirement:

ARCH-XXX: Component Identification:  The Architecture MUST provide a means to uniquely identify each Information Model and each Data Model uniquely.  The identifier MUST contain both an identifier of the model and a version indicator for the model.  The identifiers SHOULD be decomposable so that a customer can query for any version of a specific model and compare returned values for older or newer than a desired version.

**Comment by ncamwing** [comment]
I like the suggestion but I think there is only ONE SACM Information model, but there could be more than one data model.  Also, I am not sure what you mean by "Component Identification".  The abstract architecture has components to "provide", "consume", "manage" or "broker"....however, the interfaces who actually allow the components to interact must allow for the interaction to communicate the data model in use, is that what you mean? Or perhaps what you are calling out is a requirement for the information model, whereby the information model "component" that defines the interfaces must have the means to identify each data model uniquely, much to what you have.

So how about:

IM-004: Data Model Identification: The Information model MUST provide a means to uniquely identify each Data Model uniquely. The identifier MUST contain both an identifier of the model and a version indicator for the model. The identifiers SHOULD be decomposable so that a customer can query for any version of a specific model and compare returned values for older or newer than a desired version.

Thanks, Nancy.

**Comment by jimsch** [comment]
It is not at all clear to me that there is ONE SACM IM.  If there is, then the second on IM requirements seems to be something that could just be stuck into the start of that document and be done there.

I was expecting that you might end up in some different situations.
1. ```
     It is possible that the SACM IM will be decomposed for simplicity.   If there is a separate IM that deals just with endpoint identification, it can more easily be updated to deal with new devices in the future that have different types information that identifies them.  This would require an IM identifier and a version.
   ```
2. ```
     I was thinking it was possible that non SACM IMs will be integrated into the SACM system.   This would require an IM identifier and version.
   ```
3. ```
     I was thinking that it was possible that SACM like IMs will need to be created to deal with completely different situations that we don’t think about.  It might be dealt with in the future by either updating the SACM IM (thus needing a version number for the SACM IM) or by defining a new SACM IM (thus needing an identifier).
   ```

By component I was thinking in terms of exactly what the abstract architecture was defining as a component.  That is – I want to find a broker, or maybe a specific type of broker.  Alternatively, I might be looking for a specific type of evaluator to talk to.  I would also potentially want to identify data transfer protocols so I can understand from a specific component which of the different transfer protocols I have implemented to use the most efficient one.

Jim

From: ncamwing [mailto:notifications@github.com] 
Sent: Sunday, May 03, 2015 6:38 PM
To: sacmwg/draft-ietf-sacm-requirements
Cc: Jim Schaad
Subject: Re: [draft-ietf-sacm-requirements] ARCH-NEW: Component Identification (#34)

I like the suggestion but I think there is only ONE SACM Information model, but there could be more than one data model. Also, I am not sure what you mean by "Component Identification". The abstract architecture has components to "provide", "consume", "manage" or "broker"....however, the interfaces who actually allow the components to interact must allow for the interaction to communicate the data model in use, is that what you mean? Or perhaps what you are calling out is a requirement for the information model, whereby the information model "component" that defines the interfaces must have the means to identify each data model uniquely, much to what you have.

So how about:

IM-004: Data Model Identification: The Information model MUST provide a means to uniquely identify each Data Model uniquely. The identifier MUST contain both an identifier of the model and a version indicator for the model. The identifiers SHOULD be decomposable so that a customer can query for any version of a specific model and compare returned values for older or newer than a desired version.

Thanks, Nancy.

—
Reply to this email directly or view it on GitHub https://github.com/sacmwg/draft-ietf-sacm-requirements/issues/34#issuecomment-98565184 .Image removed by sender.

**Comment by ncamwing** [comment]
Hi Jim,
Given the threat in the mailer (thanks for starting it btw!), I get the sense that we're converging into 1 IM that abstract the information....perhaps we need to tighten the terminology to better reflect that, but I think we are OK now with the requirements?

Thanks, Nancy

**Comment by llorenzin** [comment]
Discussed at 6/29 virtual interim, done in -07

**Comment by jimsch** [comment]
I still worry about identification of sub IM objects, but an not going to hold this up.
