### ISSUE TITLE
OP-001 Time Synchronization

### ISSUE THREAD

**Issue by jimsch** [sacmwg/draft-ietf-sacm-requirements#39]
Version -05
1.  It really feels as if this items is imposing an architectural requirement.  That requirement being that there is a time synchronization between the components in the architecture.

ARCH-XXX Time Synchronization:  Actions or decisions based on time-sensitive data (such as user logon/logoff endpoint connection/disconnection, endpoint behaviour events, etc.) are all predicated on a synchronized understanding of time.  The SACM architecture MUST provide a mechanism for all components to be able to query for a synchronized time.  A mechanism for detecting and reporting time discrepancies SHOULD be provided by the architecture and reflected in the Information Model.
1.  I am not sure if this requirement is stating that the timestamp needs to be in the interface or if it can merely be that the recipient does the timestamp operation.  This may be different if one is looking at publishing vs querying of data.

**Comment by ncamwing** [comment]
Hi Jim,

I think you are referring to OP-001 (Time Synchronization), where we want to impose requirements that both the requests and responses be timestamped by the consumer and provider respectively.

Which does imply that there SHOULD be the means to provide a mechanism to synchronize time.  The question is whether the architecture requirement is a SHOULD vs. a MUST.....I pose the SHOULD because not all systems will want or use it, but as it is "the" SACM arch then it has to have a means to facilitate it for those who do want it.....is that why you placed the MUST?

BTW, I will add it as IM-006 and leave it as a MUST for now....

Thanks,  Nancy

**Comment by jimsch** [comment]
I think that this is a MUST requirement in terms of the architecture itself.  There is no requirement for this to be deployed in a specific location.  However if any OP is going to require that it exists, then it needs to be part of the basic architecture.

**Comment by ncamwing** [comment]
Agreed, I'll leave it as a MUST......

**Comment by jimsch** [comment]
Looks done in -06
