### ISSUE TITLE
ARCH-007 & DM-002: may vs. MAY

### ISSUE THREAD

**Issue by henkbirkholz** [sacmwg/draft-ietf-sacm-requirements#53]
In these two instances, maybe a lower case "may" should be an upper case "MAY"?

ARCH-007: "Different policies (e.g. business, regulatory, etc.) MAY specify what data may be exposed or shared by particular consumers, as well as how consumers may be required to share the information."

M-002: "Constraints and interfaces MAY further be defined to resolve or tolerate ambiguity in the references (e.g. same IP address used in two separate networks)."

**Comment by jimsch** [comment]
I totally disagree  --  What is the protocol requirement that comes out of this.  I am going to evaluate an implementation.  What do these MAY statement means in terms of deciding that the document does or does not meet the requirements.  MAY is basically- you can do this, but it is not really important to do and there is no penalty if you don't do it.

I would rather than that the requirement needs to be re-written so that it becomes a MUST statement.

ARCH-007:  "Different policies (e.g. business, regulartory, etc.) may specify what data can be exposed or shared by particular consumers, as well as how consumers may be required to share the information.  Architectures MUST define how the policies are described, how they are distributed to the appropriate providers and consumers for enforcement.

**Comment by llorenzin** [comment]
Resolution - change "may" to "might" in both cases

**Comment by llorenzin** [comment]
Fixed in -09
