### ISSUE TITLE
What is the mechanism suggested by ARCH-008?

### ISSUE THREAD

**Issue by adammontville** [sacmwg/draft-ietf-sacm-requirements#70]
What is meant by the term "mechanism" in: ""The SACM architecture MUST provide a mechanism for all components to synchronize time"?  Is this a statement about supporting timestamping?  Is it a statement suggesting that a solution should reinvent NTP?  Is it something in between?

**Comment by ncamwing** [comment]
Hi Adam,

I don't think we should be reinventing systems for timestamping; however, as SACM is creating an architecture to share information that is timestamped it needs to define how it can do so.  It is up to the group to decide how time synchronization is to occur, NTP or otherwise....but that negotiation has to be allowed in the architecture.

**Comment by adammontville** [comment]
Thanks for the clarification.

**Comment by llorenzin** [comment]
Are you okay with leaving this as-is, then?

**Comment by adammontville** [comment]
Yes, my question has been answered and I have no further comment or proposed action.
