### ISSUE TITLE
G-001: extensions and new protocols / standard and proprietary

### ISSUE THREAD

**Issue by dromasca** [sacmwg/draft-ietf-sacm-requirements#81]
G-001 reads: 

> Solution Extensibility: The information model, data models,
>     protocols, and transports defined by SACM MUST be designed to allow
>     support for future extensions, including both standard and
>     proprietary transport protocols and data models.

This seems ambiguous to me. Maybe two different issues are mixed here: 
- extending the already defined information models, data models, protocols and transports with elements, attributes, new functions that may be standard or proprietary
- supporting new data models, protocols, and transports 

For the later I am reluctant to write a requirement for extensibility with proprietary protocols or data models. Even for standard protocols and data models I believe we need to make clear that extensions MUST comply to the SACM requirements.

**Comment by ncamwing** [comment]
Hi Dan,
The intent is to have SACM be extensible in 2 dimensions:
1. SACM should be able to adapt to future requirements whether it be to allow new standard transports, protocols or data models (or extending the information model).
2. SACM should allow for vendors to use their own extensions to the information model, protocols or data model (agreed that if they do, then they are not necessarily SACM compliant).

I can see not forcing a requirement for the 2nd one, though there are quite a few standards that allow for vendor extensibility; for example, "vendor specified" attributes.  Which is why I think we added the last clause (e.g. "proprietary").

Do you have a suggestion as to how to make that more clear?  Would breaking it into the two separate bullets per the above help?

**Comment by dromasca** [comment]
Breaking this into 2 clauses makes the issues (each of them) more clear. I believe that #2 is important as well. Maybe even more important. Obviously, proprietary extensions would not be part of the standard, but they should be implementable in an easy and modular manner.

Regards,

Dan

**Comment by llorenzin** [comment]
I agree with Dan that it is as important, and possibly more important, to make sure proprietary extensions are easy to implement.  This requirement was changed in -12 from a MUST applying to both future SACM extensions and proprietary extensions, to a MUST for future SACM extensions and a SHOULD for proprietary extensions, when the requirement was broken into two clauses.  I disagree with that change and believe that the MUST should be restored, preserving the original intent of the requirement.

**Comment by llorenzin** [comment]
Consensus of 1/25 virtual interim call - change the SHOULD back to a MUST for supporting proprietary extensions.  Outside of the requirements document, SACM should encourage implementers to notify SACM of proprietary extensions - perhaps via something simple like an email to the SACM mailing list, perhaps via a more structured forum if demand arises.
